version: 2.1
jobs:
  build:
    docker:
      - image: amd64/centos:7.7.1908
    steps:
      - run:
          name: Add EPEL
          command: yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - run:
          name: Update Yum
          command: yum -y update
      - run:
          name: Install libdispatch
          command: |
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/libdispatch-1.3.1121-3.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/libdispatch-devel-1.3.1121-3.el7.x86_64.rpm
      - run:
          name: Install libobjc2
          command: |
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/libobjc2-2.0-3.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/libobjc2-devel-2.0-3.el7.x86_64.rpm
      - run:
          name: Install NextSpace Core files
          command: |
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-core-0.95-8.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-core-devel-0.95-8.el7.x86_64.rpm
      - run:
          name: Install LLVM, Clang and Git
          command: |
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/llvm-libs-7.0.1-3.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/clang-libs-7.0.1-4.el7.x86_64.rpm
            yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/clang-7.0.1-4.el7.x86_64.rpm
            yum -y install git which
      - run:
          name: GNUstep Base - install build dependencies
          command: yum -y install libffi-devel gnutls-devel openssl-devel libicu-devel libxml2-devel libxslt-devel
      - run:
          name: GNUstep Base - build and install
          command: |
            source /etc/profile.d/nextspace.sh
            CC=/usr/bin/clang
            GNUSTEP_MAKEFILES=/Developer/Makefiles
            git clone https://github.com/gnustep/libs-base
            cd libs-base
            ./configure --disable-mixedabi
            make
            make install
            ldconfig
      - run:
          name: GNUstep GUI - install build dependencies
          command: yum -y install giflib-devel libjpeg-turbo-devel libpng-devel libtiff-devel libao-devel libsndfile-devel
      - run:
          name: GNUstep GUI - build and install
          command: |
            source /etc/profile.d/nextspace.sh
            CC=/usr/bin/clang
            GNUSTEP_MAKEFILES=/Developer/Makefiles
            git clone https://github.com/gnustep/libs-gui
            cd libs-gui
            git checkout nextspace
            ./configure
            make
            make install
            ldconfig
      - run:
          name: GNUstep Back - install build dependencies
          command: yum -y install libart_lgpl-devel freetype-devel mesa-libGL-devel libX11-devel libXcursor-devel \
                   libXext-devel libXfixes-devel libXmu-devel libXt-devel libXrandr-devel
      - run:
          name:  GNUstep Back - build and install
          command: |
            source /etc/profile.d/nextspace.sh
            CC=/usr/bin/clang
            GNUSTEP_MAKEFILES=/Developer/Makefiles
            git clone https://github.com/gnustep/libs-back
            cd libs-back
            git checkout nextspace
            ./configure --enable-graphics=art --with-name=art
            make
            make fonts=no install
            ldconfig
      - checkout:
          path: /root/nextspace
      - run:
          name: Build and install Frameworks
          command: |
            cd /root/nextspace
            source /etc/profile.d/nextspace.sh
            CC=/usr/bin/clang
            cd Frameworks
            yum -y install `grep "BuildRequires" nextspace-frameworks.spec | awk -c '{print $2}'`
            make 
            make install
            ldconfig
      - run:
          name: Build and install Applications
          command: |
            cd /root/nextspace
            source /etc/profile.d/nextspace.sh
            CC=/usr/bin/clang
            cd Applications
            yum -y install `grep "BuildRequires" nextspace-applications.spec | awk -c '{print $2}'`
            cd ../Libraries/libwraster
            make 
            make install
            cd ../Applications
            make 
            make install
